#!/bin/sh
export _JAVA_AWT_WM_NONREPARENTING=1
export TERMINAL=st
killall sxhkd
setxkbmap -layout us,us -variant ,intl -option
xrandr --output HDMI-1 --primary --auto --output HDMI-0 --auto --right-of HDMI-1
#xrandr --output HDMI-1 --primary --auto --pos 0x540 --output HDMI-0 --auto --pos 1920x0
xset dpms 0 0 0
xset -dpms
numlockx on

bspc monitor HDMI-1 -d 一 二 三 四 五 六 七 八 九 十 十一
bspc monitor HDMI-0 -d 〇

bspc config border_width         4
bspc config window_gap           5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle		  false
bspc config focus_follows_pointer true

bspc config normal_border_color   "#BDAE93"
bspc config active_border_color	  "#D3869B"
bspc config focused_border_color  "#D3869B"
bspc config presel_feedback_color "#8EC07C"

bspc rule -a "jetbrains-toolbox" state=floating follow=on
bspc rule -a "blueman-manager" state=floating follow=on
bspc rule -a "Pavucontrol" state=floating
bspc rule -a "Firefox" desktop='^2'
bspc rule -a "code" desktop='^3' split_dir=south
bspc rule -a "battle.net.exe" desktop='^7'
bspc rule -a "Lutris" desktop='^8'
bspc rule -a "Steam" desktop='^8'
bspc rule -a "Spotify" desktop='^9'
bspc rule -a "discord" desktop='^10'
bspc rule -a "Thunderbird" desktop='^11'

sxhkd -c /home/nicentra/.config/sxhkd/sxhkdrc &
feh --bg-scale ~/Dropbox/Wallpapers/bg.jpg &
dropbox-cli start &
blueman-applet &
discord &
thunderbird &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
compton &
dunst &
/home/nicentra/.scripts/poly_launch.sh &
